### ISSUE TITLE
Problem to download sketch on Hidnseek IOT

### ISSUE THREAD

**Issue by Productivix** [Bucknalla/Sigfox-Hidnseek-Tutorial#1]
Hi, 
Thank you for this tuto, but I am unable to download my new sketch on my HidnSeek Iot.
I follow preciselly the tuto on my Win 10 64bits machine up to "During this period of time, a new sketch may be uploaded to the device.". May be some info are missing for a newbie like me.

As far as hardware link is concerned, I plug directly the Iot to the USB of the PC via a normal USB wire.
Compilation is Ok.

I get from Arduino 1.8.1 the following error message : 
" avrdude: Warning: cannot query manufacturer for device: No such file or directory
avrdude: Warning: cannot query product for device: Broken pipe
avrdude: error: could not find USB device with vid=0x16c0 pid=0x5dc vendor='www.fischl.de' product='USBasp' "

I looked over the web for this error message, test some issues with Zadig but no positives results.
I would appreciate your help.
Best regards
William

**Comment by Bucknalla** [comment]
Hi - 
I find that this is sometimes a problem with the COM port on Windows! I'd first suggest trying a different port on your machine and if this doesn't work, I would check your drivers. Possibly even restarting Arduino IDE might also help.

**Comment by Productivix** [comment]
hi, thanks, 
I did restart IDE many times. But how can I be sure that COM1 goes to the IOT ? 
here is the map of the connect
![capture-gestionnaire de periph](https://cloud.githubusercontent.com/assets/6737060/23265476/fcf31560-f9e4-11e6-9b48-965154d6737d.PNG)
ions 

I have also an other Ubuntu 16.04 station with IDE installed : same result. The normal USB wire is the solution , no need of an intermediate USBASP board ? Do you have a tuto for Ubunto please ? 
regards
William

**Comment by Bucknalla** [comment]
Are you shorting out the R & G pins when you connect the board? You need to do this when you want to flash the device - the led should start blinking red to let you know that its in DFU mode for the firmware upload

**Comment by Productivix** [comment]
hi, thanks, 
I did restart IDE many times. But how can I be sure that COM1 goes to the IOT ? 
here is the map of the connect
![capture-gestionnaire de periph](https://cloud.githubusercontent.com/assets/6737060/23265476/fcf31560-f9e4-11e6-9b48-965154d6737d.PNG)
ions 

I have also an other Ubuntu 16.04 station with IDE installed : same result. The normal USB wire is the solution , no need of an intermediate USBASP board ? Do you have a tuto for Ubunto please ? 
regards
William

**Comment by Productivix** [comment]
thank you : 
this has been solved on Windows that precise manner 👍 
in fact : the 30 sec sequence should be respected and it is short, so compilation time may be a problem.
So follow the steps : no stress ;-) 
1/ start download (so compile) on IDE, mentally count until 2 or 3,
2/ shortcut R & G pins and release, no led blinks
3/ immediatly connect USB wire (normal one) on IoT, red led blinks
at this moment IDE is arrives at download step and proceed,
IDE answer "download finished"  with warning : "avrdude: warning: cannot set sck period. please check for usbasp firmware update."
wait until blue led on IOT be off and unplug , it works !

**Comment by Bucknalla** [comment]
Brilliant! I'm glad you got it fixed! 👍
